#!/usr/bin/env php
<?php
/**
 * Yii console bootstrap file.
 *
 * @link http://www.yiiframework.com/
 * @copyright Copyright (c) 2008 Yii Software LLC
 * @license http://www.yiiframework.com/license/
 */

defined('YII_DEBUG') or define('YII_DEBUG', true);
defined('YII_ENV') or define('YII_ENV', 'dev');

require(__DIR__ . '/vendor/autoload.php');
require(__DIR__ . '/vendor/yiisoft/yii2/Yii.php');
require(__DIR__ . '/src/common/config/bootstrap.php');
require(__DIR__ . '/src/console/config/bootstrap.php');

$config = yii\helpers\ArrayHelper::merge(
    require(__DIR__ . '/src/common/config/main.php'),
    require(__DIR__ . '/src/common/config/main-local.php'),
    require(__DIR__ . '/src/console/config/main.php'),
    require(__DIR__ . '/src/console/config/main-local.php')
);

unset($config['as access']);

$application = new yii\console\Application($config);
$exitCode = $application->run();
echo "\n\n $exitCode \n\n";
